
from PageRank import PageRank

import time

print time.gmtime()

nodes = ['mlhkb8' \
         , 'NinoRivera' \
         , 'prideofgumbo' \
         , 'xupy' \
         , 'JosephO75' \
         , 'shirleybeans' \
         , 'drummerdude136' \
         , 'powerload' \
         , 'ultrarobin' \
         , 'saylawgun' \
         , 'Theorem' \
         , 'voicesmagazine' \
         , 'NuoVisoProductions' \
         , 'martinvist' \
         , 'jester420' \
         , 'permut20' \
         , 'euphemistic' \
         , 'artscrafts' \
         , 'Gemear' \
         , 'lyijynen' \
         , 'isac1977' \
         , 'percylynn' \
         , 'PAIKII' \
         , 'DefinitiveStar' \
         , 'NUNEX30' \
         , 'EndaMcC' \
         , 'flectz' \
         , 'jfu79' \
         , 'GhostVid' \
         , 'DrumGoh' \
         , 'orkestas' \
         , 'thedude62' \
         , 'Matsuban' \
         , 'occisMORT' \
         , 'denvercx' \
         , 'markdw40' \
         , 'redbaron863' \
         , 'leifa' \
         , 'VICERecordings' \
         , 'luchango' \
         , 'grimaldo21' \
         , 'TwangTown' \
         , 'Croketas' \
         , 'lenmacharstar' \
         , 'TankSallott' \
         , 'blackstarkitten' \
         , 'dardanella' \
         , 'killersoundz' \
         , 'davidnyren' \
         , 'sabrien' \
         , 'BayTaper' \
         , 'mattrach' \
         , 'tonictao' \
         , 'rainbow301' \
         , 'jeffro887' \
         , 'fopstra' \
         , 'nazzman' \
         , '69Lovett' \
         , 'carlosaleon' \
         , 'tjitta25' \
         , 'DrMabuse66' \
         , 'boho2007' \
         , 'toshyocom' \
         , 'rezarito' \
         , 'Guliv3r' \
         , 'mrsmorrison71' \
         , 'djcomet' \
         , 'slymetal' \
         , 'mymindazo' \
         , 'afiendishthingy' \
         , 'neslibek' \
         , 'angue' \
         , 'OrangeTabbyCat3' \
         , 'onemorecupofcoffee1' \
         , 'xalexisx3' \
         , 'grullu' \
         , 'perri23' \
         , 'sasukekun22' \
         , 'cevarius' \
         , 'iruvtea' \
         , 'rubba5k' \
         , 'southpawjay' \
         , 'toddcarey' \
         , 'isagio' \
         , 'Frutson5' \
         , 'evolvin1' \
         , 'PeaceOnEarth123' \
         , 'ferenty' \
         , 'ubhankband' \
         , 'jonbrod' \
         , 'corben47' \
         , 'jinxmaster777' \
         , 'hahatonkamusic' \
         , 'NicksterMarsh' \
         , 'MattTS01' \
         , 'netyta' \
         , 'hemo1985' \
         , 'ISTMuso' \
         , '93or93' \
         , 'dimonitxus' \
         , 'luckyoda' \
         , 'cnrsport' \
         , 'oskpeturs' \
         , 'jayeltee' \
         , 'spuddle' \
         , 'homeandgardenmusic' \
         , 'Sabaton' \
         , 'bootslover84' \
         , 'lasourisdesvilles' \
         , 'idareTocare' \
         , 'trinity1528' \
         , 'postingoldtapes' \
         , 'wwwSceneFedcom' \
         , 'bgta' \
         , 'dbneeld' \
         , 'oatzy' \
         , 'maharg11' \
         , 'TCGUITAR' \
         , 'kman518' \
         , 'michaellou' \
         , 'thehungover' \
         , 'moogdroog' \
         , 'picasso79' \
         , 'JimmyToast' \
         , 'wildbabydragon' \
         , 'dancohen' \
         , 'espeem' \
         , 'strewth' \
         , 'death2patrick' \
         , 'scarb05' \
         , 'pauldullson' \
         , 'bressane' \
         , 'ZackKim' \
         , 'Tranquility12' \
         , 'dfrohnenalfred' \
         , 'miguelcanel' \
         , 'galfredos' \
         , 'usharimau' \
         , 'lupine22' \
         , 'Americansquirm' \
         , 'TJenlared' \
         , 'DalimaaFashmire' \
         , 'TheDLShow' \
         , 'MadV' \
         , 'iburl' \
         , 'french4clouds' \
         , 'ophelia2006' \
         , 'SilviaKs' \
         , 'skankbaggins' \
         , 'waakaaboon' \
         , 'moomino' \
         , 'roio420' \
         , 'BambaMaker' \
         , 'wecurlupanddie' \
         , 'xproximusx' \
         , 'Condu100' \
         , 'MishaFromPoland' \
         , 'modnocbmallari' \
         , 'raw64life' \
         , 'reikiaddict' \
         , 'omdunet' \
         , 'CelinemaniacsCom' \
         , 'carneirooo' \
         , 'BVMHardcorePunkTV' \
         , 'S1N15T3R' \
         , 'KyuRoo' \
         , 'eu396' \
         , 'yakayakayaka' \
         , 'tiston69' \
         , 'adam02' \
         , 'pekerrecho10' \
         , 'nicofarr' \
         , 'xelectius' \
         , 'mongillo' \
         , 'Stephpekis' \
         , 'AlonzoMosleyFBI' \
         , 'afonso85' \
         , 'falconsweetwater' \
         , 'PTL654321' \
         , 'FredMartins' \
         , 'Klause' \
         , 'wispgradde' \
         , 'sapo75' \
         , 'Suchar' \
         , 'chico75pi' \
         , 'MorseMoose79' \
         , 'aprilsaurus' \
         , 'pbhack' \
         , 'djkag2006' \
         , 'missritaho' \
         , 'diOud' \
         , 'Toontrack' \
         , 'FranksValli' \
         , 'mrmanok' \
         , 'HairFarmer' \
         , 'GeorgeWaxstetter' \
         , 'deadzoner' \
         , 'gastronomist' \
         , 'robertorocky' \
         , 'dodgeturbonut' \
         , 'nembutal' \
         , 'noremorse9' \
         , 'pecomaru' \
         , 'courageousjohnny' \
         , 'metalscenetv' \
         , 'lauritaAsp18' \
         , 'JenniferH' \
         , 'PuertoRicanDivas' \
         , 'tinaarenafanes' \
         , 'druman44' \
         , 'steakcognitif' \
         , 'googirl' \
         , 'Zeolum' \
         , 'elimk' \
         , 'rspaceball' \
         , 'itat80' \
         , 'jjdaes' \
         , 'bigblueplanet' \
         , 'strawberrymj' \
         , 'fostasoti' \
         , 'dgv19711' \
         , 'intheairtonight' \
         , 'guitarjjte' \
         , 'funky2714' \
         , 'okeastron' \
         , 'raskolnikovxxl' \
         , 'bsarles' \
         , 'tasilow' \
         , 'PoisonIvy1983' \
         , 'type3secretion' \
         , '1santos1' \
         , 'gamzer' \
         , 'thejerryleelewisfan' \
         , 'juanitochiguesque' \
         , 'suziemcneil' \
         , 'TheRealJohnnyAngel' \
         , 'janemonheit' \
         , 'wcapellini' \
         , 'haaneepoo' \
         , 'Ricquer' \
         , 'LEGENDSOFJAZZ' \
         , 'fpe' \
         , 'AlexKong' \
         , 'realmusicchicago' \
         , 'hilldk11' \
         , 'kikoshred' \
         , 'vodkaa1' \
         , 'ColinQuinn' \
         , 'soFeinVideo' \
         , 'schnickschnack1990' \
         , 'FlamencoConrad' \
         , 'seitsuku' \
         , 'deniro20' \
         , 'jazzster123' \
         , 'NAUDOPRD' \
         , 'Hellbettie13' \
         , 'jaumequalsevol' \
         , 'xSlim310' \
         , 'GlennCripes' \
         , '420stud' \
         , 'cedwin' \
         , 'ElGofion' \
         , 'katonatwins' \
         , 'pakoflamenco' \
         , 'DiasdelAyer' \
         , 'cozmo' \
         , 'dawnnamara' \
         , 'WPPTV' \
         , 'Haeronthegreat' \
         , 'vagondeltren' \
         , 'salomesandoval' \
         , 'awkwardpictures' \
         , 'WiggyStHelensUK' \
         , 'DHaynesakafingerrs' \
         , 'jonboy123456' \
         , 'rizferd' \
         , 'masterrofl' \
         , 'feefree' \
         , 'malcolmmcfly' \
         , 'mastervictor' \
         , 'lerxtdude' \
         , 'mwowm23' \
         , 'sonybmg' \
         , 'petertvkill' \
         , 'schumann23' \
         , 'renewenergy' \
         , 'jazzmannl' \
         , 'hsage' \
         , 'Artiga88' \
         , 'davidaron' \
         , 'blondfalcon2' \
         , 'romainblast' \
         , 'TrueFireTV' \
         , 'tobakala' \
         , 'st1969' \
         , 'JordanChad' \
         , 'cinc' \
         , 'orphanim' \
         , 'Mondologic' \
         , 'OriginalDrDil' \
         , 'jonedryb' \
         , 'panchopistolas22' \
         , 'Dizkneelande' \
         , 'slowhand4dz' \
         , 'mulonero' \
         , 'BeckPolice' \
         , 'mattybungo' \
         , 'wackkuntucky' \
         , 'fabiocchi' \
         , 'LoveTH14' \
         , 'Trakse' \
         , 'godisatan' \
         , 'blogsarefordogs' \
         , 'edved10062' \
         , 'lexrecords' \
         , 'millinthewind' \
         , 'mathdoy' \
         , 'jazzerman' \
         , 'skunkyfunk' \
         , 'verituxsanz' \
         , 'Thor3000' \
         , 'rhubarbcream' \
         , 'ludwig222' \
         , 'BOLSHEVIK06' \
         , 'ViciousTina2006' \
         , 'WarnerMusicBelgium' \
         , 'herrstahlhoefer' \
         , 'sotti84' \
         , 'gusyverde' \
         , 'michaelsmusicservice' \
         , 'gato3d' \
         , 'coolrobbie2002' \
         , 'metalupyourassface' \
         , 'aamaa' \
         , 'Direwolf' \
         , 'slashhatim' \
         , 'electricringo' \
         , 'blonduo' \
         , 'guitres2007' \
         , 'BabyJavier21' \
         , 'EntertainmentUnited' \
         , 'Belanna42' \
         , 'robertconticom' \
         , 'yurilane' \
         , 'gdbvsdzgdsfbdfg' \
         , 'nuthead25' \
         , 'squane' \
         , 'eastvanmungo' \
         , 'Dragonzito' \
         , 'tommygauthier' \
         , 'rockhelterskelter' \
         , 'SteveMjazz' \
         , 'rusoeldelantonia' \
         , 'TravisBickle' \
         , 'JoeSiegler' \
         , 'siroco1988' \
         , 'latinthug22' \
         , 'bazonics' \
         , 'bizkitroach666' \
         , 'whatisreal01' \
         , 'oxlabb' \
         , 'chatarrito' \
         , 'phever' \
         , 'dailybean' \
         , 'anononiem' \
         , 'Ramiroquai' \
         , 'nyoung27' \
         , 't0mis' \
         , 'dandy77' \
         , 'operationuranus' \
         , 'thomasdaniel' \
         , 'yokorevolver' \
         , 'hossenff' \
         , 'Geezer3d' \
         , 'GShton' \
         , 'russaac' \
         , 'myredroom' \
         , 'fingers14' \
         , 'Albertine2006' \
         , 'outrun' \
         , 'supermilinha' \
         , 'Midwayer1111' \
         , 'peyoteshaman' \
         , 'Styles217' \
         , 'MANULE100' \
         , 'Lams9999' \
         , 'eag200' \
         , 'theinternetsmrak' \
         , 'umvideo' \
         , 'stvolo' \
         , 'ridgraycr' \
         , 'ocarametal' \
         , 'unyo303' \
         , 'loveholic6364' \
         , 'gobias33' \
         , 'j0ndaily' \
         , 'Musician81' \
         , 'katyskystar' \
         , 'elpolifemo' \
         , 'BenOrdinary' \
         , 'vip01' \
         , 'ramix2006' \
         , 'javiflamenko' \
         , 'gloria6699' \
         , 'alejandrojazzmetal' \
         , 'domthomas1' \
         , 'gugomat' \
         , 'RikiRude' \
         , 'tneorg' \
         , 'srappose' \
         , 'emruk' \
         , 'xfactorfansite' \
         , 'Kewen' \
         , 'amigomusica' \
         , 'SyClopps' \
         , 'paulyrich' \
         , 'acdeathstrike' \
         , 'ToxicEmbrace' \
         , 'fleafly' \
         , 'mmrecordinginc' \
         , 'petahx' \
         , 'AlecsMundt' \
         , 'rchaisson' \
         , 'rhythmstick' \
         , 'JOoOoDo' \
         , 'PayPalPak' \
         , 'suparni' \
         , 'criltunieddu' \
         , 'CitySlang' \
         , 'xibalbarendon' \
         , 'divingdonkey' \
         , 'Karkhash' \
         , '0Mandarina0' \
         , 'PasianEntertainment' \
         , 'HARRY24' \
         , 'wayeleongoh' \
         , 'Mando1130' \
         , 'Lucifuge' \
         , 'boogieman69' \
         , 'ricomachiavelli' \
         , 'Scarab75' \
         , 'kubes' \
         , 'halipino' \
         , 'gregplaysthestick' \
         , 'ImperfectxCircle' \
         , 'expositionanormale' \
         , 'deathcrab' \
         , 'Casshern25' \
         , 'LAHFaust' \
         , 'noinfluence' \
         , 'przemkam' \
         , 'Nouveauxromo' \
         , 'ljubisab' \
         , 'srsnoid' \
         , 'williebeable2c' \
         , 'Pkw101' \
         , 'deepfreezevideo' \
         , 'Sethtann' \
         , 'argondamn' \
         , 'TSMusVid' \
         , 'worldchallenger' \
         , 'luizdamata' \
         , 'Louie566' \
         , 'LasAntOne' \
         , 'datishet' \
         , 'robertkittila' \
         , 'bakachibi' \
         , 'Ashstarr' \
         , 'scotchhollow' \
         , 'fantacolaspezi' \
         , 'evandronew' \
         , 'Exequian' \
         , 'ifstudents' \
         , 'LeGauchiste' \
         , 'TravBurcham' \
         , 'naom6654321' \
         , 'Lakin24' \
         , 'johngreek' \
         , 'veefan1963' \
         , 'jazzfunkshizzle' \
         , 'uniqlomixer' \
         , 'BASSMAN455' \
         , 'agwtube' \
         , 'askox' \
         , 'abstractlogix23' \
         , 'thestandingroom' \
         , 'Humphreysguitar' \
         , 'caroline372' \
         , 'norske3n' \
         , 'Kassandra22' \
         , 'jazzerkris' \
         , 'davegahanofficial' \
         , 'athenian1977' \
         , 'GigiBrasil' \
         , 'BigEvilSDMF' \
         , 'matteo19' \
         , 'Elvistagger' \
         , 'ConnorTheSlayer' \
         , 'langwave' \
         , 'secretcityrecords' \
         , 'Scot90230' \
         , 'romire' \
         , 'heyjude421' \
         , 'doer62' \
         , 'MoodiesFan' \
         , 'mickm305' \
         , 'akoff' \
         , 'trfrasier' \
         , 'Lahed92801' \
         , 'willbill0587' \
         , 'FearlessRecords' \
         , 'saitow' \
         , 'berg444' \
         , 'menudanochecanalsur' \
         , 'bandasurdo' \
         , 'thedoorsofthefuture' \
         , 'danielflorencio' \
         , 'MerkinAbowt' \
         , 'shapirog' \
         , 'chronicbluntman420' \
         , 'phatterboy' \
         , 'blhsing' \
         , 'Endrias' \
         , 'kostlawankenobi' \
         , 'lethrneck4' \
         , 'MrFinseth' \
         , 'Kushrynada' \
         , 'jackliveshere2' \
         , 'maceoaus' \
         , 'spaceace40' \
         , 'dhrrltka' \
         , 'bird5050' \
         , 'Xexezinha' \
         , 'spazmodica2012' \
         , 'Orville9999' \
         , 'gustavopoeta' \
         , 'pujaben' \
         , 'latin60' \
         , 'EnigmaSolved' \
         , 'letthemetalflow' \
         , 'fhita' \
         , 'largofilm' \
         , 'karlys18' \
         , 'kootallica' \
         , 'carmbler' \
         , 'Stanbush86' \
         , 'DOWN2WHISKEY' \
         , 'mobiusII' \
         , 'alejandraleiva7' \
         , 'sirdynozxiv' \
         , 'pixaninny' \
         , 'melissa3110' \
         , 'PACARTNEY' \
         , 'LAGUATEKE' \
         , 'lotto2' \
         , 'certifiedpirate' \
         , 'neokyle' \
         , 'ballbeg' \
         , 'PetesBloodyHand' \
         , 'hulldanfan' \
         , 'brian278' \
         , 'losderibadumia' \
         , 'Lezcanomg' \
         , 'bruckkk' \
         , 'gelido95' \
         , 'TymonExivious' \
         , 'davebarrett81' \
         , 'corporatecountrysuck' \
         , 'BeatnikManfred' \
         , 'primative276' \
         , 'keppler' \
         , 'MrPhotomatic' \
         , 'KeizerSosa' \
         , 'drednought77' \
         , 'mikus1983' \
         , 'deemackproduction69' \
         , 'butalcain' \
         , 'babygus93' \
         , 'chiwawette33' \
         , 'ChuckAkins' \
         , 'nandowainwright' \
         , 'luisguilhermeolbertz' \
         , 'seyit0123' \
         , 'B0zz3' \
         , 'lomoncurry' \
         , 'ballesterom' \
         , 'vicioustruth' \
         , 'GMiner' \
         , 'Consulina' \
         , 'julianpineirua' \
         , 'GreatSpeckledBird' \
         , 'TOMSOUNDS' \
         , 'Gusyverde2' \
         , 'caaaroooooo' \
         , 'officialstp' \
         , 'Molgav' \
         , 'arsenal76' \
         , 'MissVerdugo' \
         , 'FilomenaMorettiVIDS' \
         , 'limiardorock' \
         , 'lakme' \
         , 'acompas' \
         , 'mgng' \
         , 'johnmayer' \
         , 'donmauro24' \
         , '80sLady' \
         , 'snowbot79' \
         , 'penaytristeza' \
         , 'ELCIDVIVAR' \
         , 'idekan' \
         , 'lettieb13' \
         , 'pedrogamo' \
         , 'drdoowop' \
         , 'pitchipich' \
         , 'gobacktogo' \
         , 'erikmongrain' \
         , 'pulsepi' \
         , 'antoniomanco' \
         , 'fastfocustv' \
         , 'backpackdave' \
         , 'cbrace' \
         , 'Moiseocb' \
         , 'vds123vds123' \
         , 'davidvaldes' \
         , 'scoobyman' \
         , 'okfer' \
         , 'mindbank' \
         , 'jonnyb666' \
         , 'conquestfordeath32' \
         , 'wiggindude' \
         , 'marks6338' \
         , 'doigman' \
         , 'Vicdp' \
         , 'andreasoberg' \
         , 'chikka1971' \
         , 'thepolonaise' \
         , 'beet1ejuicex3' \
         , 'alwiap15' \
         , 'CafeDaria' \
         , 'TheDoorsMusic' \
         , 'musiquesimilia' \
         , 'songbird1987' \
         , 'DJFPhantomPhan' \
         , 'Hippekuln' \
         , 'addyd01' \
         , 'terminusj' \
         , 'deenichols' \
         , 'rubiarock' \
         , 'haveyouseenmygoal' \
         , 'Teenagekicks' \
         , 'Harrybigloaf' \
         , 'maurilyn' \
         , 'peterfriday' \
         , 'oligore' \
         , 'LAZ61' \
         , 'patzu' \
         , 'Pasquerel' \
         , 'mikerjohnson' \
         , 'caveman78' \
         , 'musicmasterez' \
         , 'Snidress' \
         , 'Napolianboo' \
         , 'jimmyjoeroche' \
         , 'scmm42' \
         , 'bigwhitneyfan' \
         , 'homewalk' \
         , 'mitzy1234' \
         , 'enunc8r' \
         , 'Czitar' \
         , 'jacquesmees' \
         , 'tracydanger' \
         , 'hctibytipidneres' \
         , 'pakomusicalatino' \
         , 'DXlovesEDBD' \
         , 'ssg410' \
         , 'camaronnuestro' \
         , 'BiggerThanYou' \
         , 'CARADEYONOFUI' \
         , 'MKT2' \
         , 'Saxatilis9876' \
         , 'emzypoo3' \
         , 'Joseppi' \
         , 'superraiden' \
         , 'Lion7718' \
         , 'rbunbury' \
         , 'Metalized' \
         , 'francky85' \
         , 'paris1919' \
         , 'nldisco' \
         , 'gloomferret' \
         , 'Yulieta' \
         , 'WagnerOperas' \
         , 'superh7' \
         , 'honouredman' \
         , 'enjoybellwoods' \
         , 'Damalmansa' \
         , 'zahnyx' \
         , '3inchesofbloodtv' \
         , 'monmonsnow' \
         , 'christinah3000' \
         , 'rockonyemenofwar' \
         , 'Miko1p' \
         , 'paulcapewell' \
         , 'muz1kf0rever' \
         , 'misterdopeman' \
         , 'vicarinatutugal' \
         , 'tHoM0r' \
         , 'norteflamenco' \
         , 'WarpRecords' \
         , 'Levesque999' \
         , 'stazisummers' \
         , 'rpoland' \
         , 'sgtpepper2' \
         , 'diablofn' \
         , 'MrsDinoCrocetti' \
         , 'anubysath' \
         , 'Sharpmarkers' \
         , 'NettwerkMusic' \
         , 'thebeatlessound' \
         , 'osvaldo05' \
         , 'bigotitus' \
         , 'tradestaff' \
         , 'denSMSgt' \
         , 'vparadis' \
         , 'davidjepank' \
         , 'elmagopickup' \
         , 'kemadordcdman' \
         , 'diegodf87' \
         , 'NRDCflix' \
         , 'stoneagelightning' \
         , 'kabemty' \
         , 'personatv' \
         , 'musich3ad' \
         , 'texasitch' \
         , 'nolimits67' \
         , 'Firebirdth' \
         , 'wildeyed' \
         , 'DrCochambre' \
         , 'asturmod2' \
         , 'TheSw1tch' \
         , 'Junttidiskokunkku' \
         , 'GuitarPlayerMatthew' \
         , 'aarnouddegroen' \
         , 'CLARUSBARTEL72' \
         , 'monroe12478' \
         , 'GreenElmer' \
         , 'showbizmanager9' \
         , 'stoffershorty' \
         , 'blondie92126' \
         , 'monkeytail713' \
         , 'asiantiger01' \
         , 'raphaeldesi2' \
         , 'blaubeeri666' \
         , 'ludwigtrap' \
         , 'xSUPERFUZZx' \
         , 'joooosu' \
         , 'titosiroco' \
         , 'charnes' \
         , 'ritaclips' \
         , 'Greyful' \
         , 'verme87' \
         , 'usedMTVpromos' \
         , 'glorfo' \
         , 'GreatSouthern' \
         , 'classicalguild' \
         , 'Dixierocks20' \
         , 'insandiego' \
         , 'arkeolog99' \
         , 'Elwing06' \
         , 'caccataylor' \
         , '4sky13' \
         , 'russelljdj' \
         , 'billyjoel' \
         , 'FattyJubbo' \
         , 'gonainie' \
         , 'daniloprado' \
         , 'emixdub' \
         , 'Chapmanfan' \
         , 'troubleclef' \
         , 'NewNuma' \
         , 'HansVonz' \
         , 'Sudarev' \
         , 'bobroets' \
         , 'tapsomebong' \
         , 'Stillremains' \
         , 'lamofo' \
         , 'totalgrobanite' \
         , 'darkerstuff' \
         , 'carrotjuice78' \
         , 'caseymagic' \
         , 'claddagh15' \
         , 'duncansheiktv' \
         , 'keysnovello' \
         , 'hand42' \
         , 'edugiansante' \
         , 'LoveUprising' \
         , 'Nd179' \
         , 'NezHEAD66' \
         , 'Samanosuke2' \
         , 'spockula' \
         , 'BenRodenburg' \
         , 'Ro18' \
         , 'Ayhoe' \
         , 'omar2x' \
         , 'Enyzam' \
         , 'CelineAndRene' \
         , 'makijackal' \
         , 'mikeknein' \
         , 'kippledodo' \
         , 'hn999' \
         , 'viniciusmc' \
         , 'ahoy16' \
         , 'ALIONBASS' \
         , 'gatasalvaje79' \
         , 'Hafor' \
         , 'stever1957' \
         , 'retrovintage' \
         , 'edbazs' \
         , 'ilamvm' \
         , 'footfoot1983' \
         , 'garyhopkins' \
         , 'juarmaELSOCIO' \
         , 'llafutaal' \
         , 'soygitano' \
         , 'david140863' \
         , 'NuclearBlastEurope' \
         , 'McCartney8897' \
         , 'panch85' \
         , 'VJmongo' \
         , 'alexvmusic' \
         , 'lorelay' \
         , 'pauliethepunk' \
         , 'PetroBPettson' \
         , 'alvastarr' \
         , 'tpet32' \
         , 'esyooee' \
         , 'litigioushipster' \
         , 'grunzy' \
         , 'bert839550' \
         , 'bubbleplastik' \
         , 'chudnovsky' \
         , 'Funesolea' \
         , 'wiljay' \
         , 'Xbxg32000' \
         , 'xyzmikey1' \
         , 'gotitans999' \
         , 'frankorrall' \
         , 'PiatyElefant' \
         , 'remos74' \
         , 'doule' \
         , 'cheeryvibez' \
         , 'Update0704' \
         , 'MattAlexan' \
         , 'qech' \
         , 'rpmime' \
         , 'OldhamAthletic87KTF' \
         , 'breckerfan' \
         , 'kawryan' \
         , 'kerryberrywerry' \
         , 'ralphdude' \
         , 'kanengiser' \
         , 'gasol777' \
         , 'todgemistro' \
         , 'Blunty3000' \
         , 'videosimard' \
         , 'akadai' \
         , 'nephilim3' \
         , 'marRicardo' \
         , 'pichfl' \
         , 'videotrading' \
         , 'NiliWafers' \
         , 'lomiek' \
         , 'vemendoza' \
         , 'jbbaja' \
         , 'TampaFred' \
         , 'Hellbillyriot42' \
         , 'upfahler' \
         , 'universalmusicgroup' \
         , 'PUNKsir' \
         , 'heavymetalsourcepr' \
         , 'msusparty2000' \
         , 'RavenNation' \
         , 'sassasdotorg' \
         , 'pianorgano' \
         , 'fsas06' \
         , 'TotalVoltageVault' \
         , 'Odiesseo' \
         , 'GTI8855' \
         , 'denovodahl' \
         , 'metebelis' \
         , 'lightman' \
         , 'moodyb' \
         , '66BUDOKAN' \
         , 'harryuhf' \
         , 'gtrcoach' \
         , 'billieandmarty' \
         , 'hmbscully' \
         , 'esmirriao84' \
         , 'magicbologna' \
         , 'Lisi140' \
         , 'davidportugheis' \
         , 'tomsanti' \
         , 'sonicreality' \
         , 'amarelo' \
         , 'nmhu77' \
         , 'PamBeatabet' \
         , 'peteruia' \
         , 'maxider' \
         , 'fredcyr' \
         , 'chuknano' \
         , 'tallerdemusics' \
         , 'lsfilho' \
         , 'GuitarRusso' \
         , 'IckeundEr' \
         , 'Filmstudent89' \
         , 'HolgerregloH' \
         , 'MusicIdiotSavante' \
         , 'jpgetty' \
         , 'showbiz87' \
         , 'crappco' \
         , 'Committed77' \
         , 'Raggapants' \
         , 'theotherone61' \
         , 'somebod' \
         , 'comedyconn' \
         , 'tivogliobene85' \
         , 'nutaswhitco' \
         , 'tobeface' \
         , 'Roberttheluthier' \
         , 'paswitzer' \
         , 'INDIOBRAVO' \
         , 'shatterdwing' \
         , 'patjeuitgils' \
         , 'meesteraldous' \
         , 'calamityjames' \
         , 'TayZonday' \
         , 'eclypso' \
         , 'username999999999' \
         , 'vw86gti' \
         , 'serbo' \
         , 'torkbabe67' \
         , 'BastardSonOfGod' \
         , 'ThePrairiePrankster' \
         , 'austinstein' \
         , 'halherta' \
         , 'emalyse' \
         , 'vinkes' \
         , 'steamrocks' \
         , 'dramaqueen43' \
         , 'vnblueberry' \
         , 'zindabada' \
         , 'PAULASOVERAL' \
         , 'freedomworksfilms' \
         , 'enemy4monotoniclife' \
         , 'danielperson' \
         , 'sintoniasaintgermain' \
         , 'zizter' \
         , 'Fury' \
         , 'elenarendezvous' \
         , 'harmypochi' \
         , 'hippieschnitzel' \
         , 'GameFreak7885' \
         , 'superpicker' \
         , 'Brutal561E' \
         , 'blindlemonlemonhead' \
         , 'DoowopRick' \
         , 'n0b0dysbitch0' \
         , 'kurdtss' \
         , 'Funkonaut' \
         , 'LordofDoom202' \
         , 'dangelo87' \
         , 'xAdaliax' \
         , 'hartiganxxx' \
         , 'PatyDifusa' \
         , 'oysteryogurt' \
         , 'vdj' \
         , 'austinmayor' \
         , 'SoloGuitaristNet' \
         , 'germanyonline' \
         , 'guitaroo1' \
         , 'haithamflamenco' \
         , 'weba' \
         , 'FrostyMorn' \
         , 'gitaniyaheredia' \
         , 'walkinthemire' \
         , 'nfscoy' \
         , 'bartola67' \
         , 'ccbopcarp' \
         , 'avondmaal' \
         , 'galleis2' \
         , 'Suldarr' \
         , 'mrdodo' \
         , 'JsinDiablo' \
         , 'marcusd' \
         , 'modpete' \
         , 'elizabeth2212' \
         , 'lubitel11' \
         , 'PaCobble' \
         , 'ta55555555' \
         , 'bearshimmy1' \
         , 'carhornsinapril' \
         , 'maxeypad' \
         , 'niquele' \
         , 'sunserious' \
         , 'roadrunnerrecords' \
         , 'Nafoute' \
         , 'giottocimabue' \
         , 'JAustinDuke' \
         , 'Followthatkite' \
         , 'Partyslammer' \
         , 'mattmanmoo' \
         , 'DissolvedGirl' \
         , 'CantStandYaCostanza' \
         , 'anrongliang' \
         , 'AcidPhase15' \
         , 'rorad7' \
         , 'claudiusfr02' \
         , 'summerseve' \
         , 'pabloancieta' \
         , 'rebel072162' \
         , 'CarpentersSuperstars' \
         , 'LickByNeckDotCom' \
         , 'zombierichard' \
         , 'heavyrevolution' \
         , 'Foskateer' \
         , 'enmasse' \
         , 'whiteSM05' \
         , 'zinta2000' \
         , 'ESCManiac' \
         , 'greenmillcorp' \
         , 'Mag141414' \
         , 'clates' \
         , 'RCRENTER' \
         , 'iheartguitars83' \
         , 'Fstyl' \
         , 'MMLeung' \
         , 'neurophilemichel' \
         , 'fatgirlgrobie' \
         , 'fpdiii' \
         , 'CompayHabana' \
         , 'jwcfree' \
         , 'SGSabbathPlayer' \
         , 'kissmaniak' \
         , 'blocpartyofficial' \
         , 'kissdemonette' \
         , 'nowitslemon' \
         , 'TotallyDionne' \
         , 'Stillborn01' \
         , 'playguitarsolos' \
         , '7arsehle6' \
         , 'siggi5153' \
         , 'rushdan' \
         , 'razel01' \
         , 'musiciansworkshop' \
         , 'asherel' \
         , 'Fallschirmjager' \
         , 'mattharding2718' \
         , 'fngrpckr' \
         , 'albertparsley' \
         , 'pippintk' \
         , 'kenstannuurd' \
         , 'USAsoccer2010' \
         , 'HateSphereSickness' \
         , 'opevans' \
         , 'eltonb' \
         , 'morrisseymylove' \
         , 'MAXI230384' \
         , 'foniberico' \
         , 'Reactivate010' \
         , 'fasumia' \
         , 'lightning49' \
         , 'skyhog' \
         , 'sickboy888' \
         , 'lauranbri' \
         , 'markuskoenig' \
         , 'vac' \
         , 'phaedor' \
         , 'frommelxp' \
         , 'dfurn' \
         , 'corporeal' \
         , 'deadliner' \
         , 'BSHQ' \
         , 'lancetrumbull' \
         , 'blacklotus007' \
         , 'dexter63' \
         , 'pencilpusher30' \
         , 'ReverendBeastly' \
         , 'fritzita' \
         , 'polaris20' \
         , 'sambo191' \
         , 'tisizemenrai' \
         , 'HenfieldWill' \
         , 'vgarambone' \
         , 'LuiscmckII' \
         , 'jonemmerling' \
         , 'percivaljulio' \
         , 'RAKIMWILLIAM' \
         , 'maldroid1' \
         , 'shifzr' \
         , 'jamieza' \
         , 'CardboardBudda' \
         , 'Mukasz' \
         , 'dukels' \
         , 'sebas71' \
         , 'fsultra' \
         , 'sgbnyc' \
         , 'phalopalo' \
         , 'paperhearts07' \
         , 'dancebuffet' \
         , 'Terriman' \
         , 'lossilencios' \
         , 'masterwiz26' \
         , 'Greg08101995' \
         , 'mayermusic' \
         , 'juliocvr17' \
         , 'isntitironicRACOON' \
         , 'dutchfellow' \
         , 'RickRudesMustache' \
         , 'buffalax' \
         , 'deliciousvinyl' \
         , 'shaf747' \
         , 'loulou7803' \
         , 'pizadio' \
         , 'doradorecords' \
         , 'plasticwrapcharlie' \
         , 'baladistadecorazon' \
         , 'maknstfe' \
         , 'progressspirit' \
         , 'ctseng' \
         , 'AntoineDufour' \
         , 'vargasxerez' \
         , 'drunkhorse' \
         , 'locho36' \
         , 'aconradescu' \
         , 'figgybit' \
         , 'Zazzarelle' \
         , 'JPL1982' \
         , 'itaydovrin' \
         , 'semillanegra00' \
         , 'tlsbr' \
         , 'WCHANDY' \
         , 'moresco63' \
         , 'quinny63' \
         , 'megbro' \
         , 'patandcliff' \
         , 'koioti' \
         , 'lu4ofa' \
         , 'itsartolie' \
         , 'reenee' \
         , 'Salfordian' \
         , 'nichols8917' \
         , 'daandrums' \
         , 'beatdacy' \
         , 'Mustainexd' \
         , 'wichitarecordings' \
         , 'BDP62' \
         , 'BenOwensGuitardotcom' \
         , 'Artero' \
         , 'stegor' \
         , 'cosmicrocketman' \
         , 'snark12' \
         , 'MorningDewUS' \
         , 'TheClash0711' \
         , 'shumpy' \
         , 'carlus88' \
         , 'CrunchyWacko' \
         , 'weirdcollector' \
         , 'jazzsanjavier' \
         , 'heavyarms117' \
         , 'WhenSwingWasKing' \
         , 'katahira' \
         , 'AHicks200' \
         , 'classics2dvdDOTcom' \
         , 'ShoTown' \
         , 'maikecau' \
         , 'dieselbytes' \
         , 'pongopigmayiss' \
         , 'boh3m3' \
         , 'Fretkillr' \
         , 'rainandwater001' \
         , 'deldea' \
         , 'jasabet' \
         , 'Vreci' \
         , 'dylg' \
         , 'matttheguitarist' \
         , 'RadioMad' \
         , 'guitar122334' \
         , 'grandiosity' \
         , 'NilezII' \
         , 'BillyMacMusic' \
         , 'mozman68' \
         , 'simonjung' \
         , 'warz00' \
         , 'FibonacciPrower' \
         , 'asfaltico' \
         , 'TheLKfanClub' \
         , 'Bukk3tbot' \
         , 'mirageuk' \
         , 'aerboarder' \
         , 'edwardnorton' \
         , 'richcapo' \
         , 'modcentric' \
         , 'freakslique' \
         , 'Boatv2' \
         , 'bohemion' \
         , 'videogum' \
         ]

edges = [('lerxtdude','patjeuitgils') \
         , ('kerryberrywerry','unyo303') \
         , ('SoloGuitaristNet','phalopalo') \
         , ('fritzita','GTI8855') \
         , ('alexvmusic','phever') \
         , ('emalyse','jpgetty') \
         , ('roadrunnerrecords','Stillremains') \
         , ('russelljdj','snowbot79') \
         , ('snowbot79','acdeathstrike') \
         , ('emalyse','spuddle') \
         , ('buffalax','comedyconn') \
         , ('69Lovett','ferenty') \
         , ('intheairtonight','alejandraleiva7') \
         , ('elizabeth2212','arsenal76') \
         , ('gusyverde','gugomat') \
         , ('schumann23','jeffro887') \
         , ('amigomusica','LasAntOne') \
         , ('Orville9999','LAHFaust') \
         , ('sasukekun22','pianorgano') \
         , ('intheairtonight','Harrybigloaf') \
         , ('DrCochambre','asfaltico') \
         , ('gatasalvaje79','Kassandra22') \
         , ('neokyle','thehungover') \
         , ('euphemistic','LasAntOne') \
         , ('juanitochiguesque','aconradescu') \
         , ('musicmasterez','seyit0123') \
         , ('alejandrojazzmetal','bazonics') \
         , ('Yulieta','lotto2') \
         , ('intheairtonight','sonicreality') \
         , ('russelljdj','maxider') \
         , ('Vreci','Fretkillr') \
         , ('dimonitxus','menudanochecanalsur') \
         , ('HairFarmer','stegor') \
         , ('NilezII','certifiedpirate') \
         , ('BSHQ','percylynn') \
         , ('schumann23','muz1kf0rever') \
         , ('totalgrobanite','dandy77') \
         , ('HairFarmer','vw86gti') \
         , ('evolvin1','jazzster123') \
         , ('roadrunnerrecords','xAdaliax') \
         , ('Direwolf','metalupyourassface') \
         , ('Nd179','gloomferret') \
         , ('jazzfunkshizzle','modpete') \
         , ('edugiansante','monroe12478') \
         , ('rezarito','slowhand4dz') \
         , ('euphemistic','DrumGoh') \
         , ('musicmasterez','Ashstarr') \
         , ('alejandrojazzmetal','latinthug22') \
         , ('sasukekun22','MANULE100') \
         , ('rezarito','blhsing') \
         , ('alejandrojazzmetal','elpolifemo') \
         , ('pencilpusher30','duncansheiktv') \
         , ('intheairtonight','claudiusfr02') \
         , ('blonduo','mrsmorrison71') \
         , ('matteo19','paperhearts07') \
         , ('jazzfunkshizzle','ALIONBASS') \
         , ('erikmongrain','lancetrumbull') \
         , ('JPL1982','davegahanofficial') \
         , ('AntoineDufour','tommygauthier') \
         , ('tiston69','mwowm23') \
         , ('CARADEYONOFUI','progressspirit') \
         , ('russelljdj','Gusyverde2') \
         , ('elizabeth2212','akadai') \
         , ('bird5050','lenmacharstar') \
         , ('ELCIDVIVAR','fsultra') \
         , ('scoobyman','anubysath') \
         , ('roadrunnerrecords','fpe') \
         , ('amigomusica','hctibytipidneres') \
         , ('Levesque999','fsas06') \
         , ('BSHQ','kawryan') \
         , ('amigomusica','katahira') \
         , ('JPL1982','SGSabbathPlayer') \
         , ('blonduo','thedoorsofthefuture') \
         , ('emalyse','markuskoenig') \
         , ('eastvanmungo','GreatSpeckledBird') \
         , ('elizabeth2212','veefan1963') \
         , ('thomasdaniel','JordanChad') \
         , ('DrCochambre','bubbleplastik') \
         , ('elizabeth2212','rainandwater001') \
         , ('roadrunnerrecords','addyd01') \
         , ('Nd179','GhostVid') \
         , ('masterrofl','lamofo') \
         , ('MadV','lexrecords') \
         , ('amigomusica','xproximusx') \
         , ('paris1919','AlexKong') \
         , ('aprilsaurus','marcusd') \
         , ('koioti','scarb05') \
         , ('alejandrojazzmetal','mattybungo') \
         , ('amigomusica','PayPalPak') \
         , ('simonjung','angue') \
         , ('JPL1982','wispgradde') \
         , ('soygitano','jeffro887') \
         , ('marks6338','breckerfan') \
         , ('Louie566','Lahed92801') \
         , ('DJFPhantomPhan','yakayakayaka') \
         , ('scoobyman','cedwin') \
         , ('buffalax','Mukasz') \
         , ('roadrunnerrecords','3inchesofbloodtv') \
         , ('marks6338','nicofarr') \
         , ('BSHQ','MrFinseth') \
         , ('fritzita','peteruia') \
         , ('camaronnuestro','Midwayer1111') \
         , ('elizabeth2212','MoodiesFan') \
         , ('thebeatlessound','DiasdelAyer') \
         , ('russelljdj','Louie566') \
         , ('russelljdj','blonduo') \
         , ('euphemistic','scoobyman') \
         , ('bsarles','sirdynozxiv') \
         , ('expositionanormale','electricringo') \
         , ('tiston69','bgta') \
         , ('trfrasier','j0ndaily') \
         , ('eastvanmungo','ViciousTina2006') \
         , ('thebeatlessound','baladistadecorazon') \
         , ('NilezII','skyhog') \
         , ('ELCIDVIVAR','USAsoccer2010') \
         , ('JPL1982','Odiesseo') \
         , ('Vreci','vnblueberry') \
         , ('musicmasterez','Elvistagger') \
         , ('tradestaff','emalyse') \
         , ('erikmongrain','Orville9999') \
         , ('WPPTV','Exequian') \
         , ('scoobyman','sapo75') \
         , ('totalgrobanite','kippledodo') \
         , ('lerxtdude','Toontrack') \
         , ('Moiseocb','universalmusicgroup') \
         , ('buffalax','dailybean') \
         , ('fritzita','videotrading') \
         , ('NilezII','BeckPolice') \
         , ('kawryan','prideofgumbo') \
         , ('WPPTV','mikeknein') \
         , ('jazzfunkshizzle','Reactivate010') \
         , ('1santos1','bobroets') \
         , ('picasso79','tobeface') \
         , ('rpoland','caccataylor') \
         , ('scoobyman','TampaFred') \
         , ('sasukekun22','Matsuban') \
         , ('phever','summerseve') \
         , ('russelljdj','bird5050') \
         , ('BSHQ','hahatonkamusic') \
         , ('fritzita','permut20') \
         , ('snowbot79','WhenSwingWasKing') \
         , ('Greg08101995','boogieman69') \
         , ('amigomusica','johnmayer') \
         , ('intheairtonight','fostasoti') \
         , ('trfrasier','srsnoid') \
         , ('sgbnyc','bressane') \
         , ('thomasdaniel','thejerryleelewisfan') \
         , ('emalyse','penaytristeza') \
         , ('progressspirit','Lisi140') \
         , ('BOLSHEVIK06','INDIOBRAVO') \
         , ('jazzfunkshizzle','serbo') \
         , ('bird5050','mattmanmoo') \
         , ('expositionanormale','jfu79') \
         , ('pichfl','IckeundEr') \
         , ('Nd179','sonybmg') \
         , ('koioti','davidportugheis') \
         , ('trfrasier','HairFarmer') \
         , ('Louie566','PACARTNEY') \
         , ('sasukekun22','rbunbury') \
         , ('BenOrdinary','theinternetsmrak') \
         , ('1santos1','JsinDiablo') \
         , ('jazzfunkshizzle','WiggyStHelensUK') \
         , ('alejandrojazzmetal','BastardSonOfGod') \
         , ('JPL1982','kissmaniak') \
         , ('MadV','voicesmagazine') \
         , ('somebod','emruk') \
         , ('Louie566','robertconticom') \
         , ('rpoland','euphemistic') \
         , ('HairFarmer','jazzmannl') \
         , ('edugiansante','xelectius') \
         , ('marks6338','mobiusII') \
         , ('asherel','ramix2006') \
         , ('Nd179','Boatv2') \
         , ('iburl','nutaswhitco') \
         , ('GShton','millinthewind') \
         , ('1santos1','GreenElmer') \
         , ('AntoineDufour','tradestaff') \
         , ('edugiansante','erikmongrain') \
         , ('erikmongrain','koioti') \
         , ('javiflamenko','juarmaELSOCIO') \
         , ('todgemistro','HenfieldWill') \
         , ('Direwolf','GreatSouthern') \
         , ('soygitano','francky85') \
         , ('bird5050','mmrecordinginc') \
         , ('ThePrairiePrankster','osvaldo05') \
         , ('trfrasier','marks6338') \
         , ('russelljdj','Mando1130') \
         , ('marks6338','cozmo') \
         , ('mattharding2718','NettwerkMusic') \
         , ('amigomusica','PaCobble') \
         , ('totalgrobanite','christinah3000') \
         , ('erikmongrain','lerxtdude') \
         , ('BSHQ','eastvanmungo') \
         , ('erikmongrain','t0mis') \
         , ('hsage','tiston69') \
         , ('LasAntOne','polaris20') \
         , ('Louie566','robertkittila') \
         , ('Geezer3d','guitarjjte') \
         , ('tradestaff','guitaroo1') \
         , ('HenfieldWill','rorad7') \
         , ('schumann23','kostlawankenobi') \
         , ('roadrunnerrecords','DXlovesEDBD') \
         , ('Louie566','ocarametal') \
         , ('marks6338','Mondologic') \
         , ('mathdoy','deemackproduction69') \
         , ('gobias33','deadzoner') \
         , ('LasAntOne','deadliner') \
         , ('tasilow','warz00') \
         , ('schumann23','thepolonaise') \
         , ('javiflamenko','NUNEX30') \
         , ('austinmayor','clates') \
         , ('javiflamenko','mulonero') \
         , ('austinmayor','Joseppi') \
         , ('simonjung','xibalbarendon') \
         , ('Tranquility12','Pkw101') \
         , ('killersoundz','NiliWafers') \
         , ('1santos1','patandcliff') \
         , ('tradestaff','superh7') \
         , ('raw64life','xSlim310') \
         , ('russelljdj','thomasdaniel') \
         , ('HenfieldWill','Vicdp') \
         , ('MadV','boho2007') \
         , ('Vreci','Humphreysguitar') \
         , ('expositionanormale','lorelay') \
         , ('russelljdj','thebeatlessound') \
         , ('tlsbr','moomino') \
         , ('BSHQ','doigman') \
         , ('evolvin1','fingers14') \
         , ('trfrasier','kissdemonette') \
         , ('Geezer3d','MattAlexan') \
         , ('expositionanormale','death2patrick') \
         , ('freedomworksfilms','Blunty3000') \
         , ('eastvanmungo','torkbabe67') \
         , ('Nd179','Enyzam') \
         , ('HairFarmer','carmbler') \
         , ('picasso79','rubba5k') \
         , ('bird5050','nazzman') \
         , ('todgemistro','intheairtonight') \
         , ('ELCIDVIVAR','Zazzarelle') \
         , ('camaronnuestro','vagondeltren') \
         , ('expositionanormale','Xbxg32000') \
         , ('dimonitxus','PAIKII') \
         , ('FranksValli','chudnovsky') \
         , ('tlsbr','mymindazo') \
         , ('evolvin1','LordofDoom202') \
         , ('killersoundz','CardboardBudda') \
         , ('eastvanmungo','xSUPERFUZZx') \
         , ('Moiseocb','chuknano') \
         , ('amigomusica','sambo191') \
         , ('BenOrdinary','dfurn') \
         , ('camaronnuestro','verituxsanz') \
         , ('Gusyverde2','gusyverde') \
         , ('Vreci','Roberttheluthier') \
         , ('asherel','occisMORT') \
         , ('bird5050','albertparsley') \
         , ('NilezII','Raggapants') \
         , ('lerxtdude','TymonExivious') \
         , ('edugiansante','rpoland') \
         , ('todgemistro','tlsbr') \
         , ('camaronnuestro','lauritaAsp18') \
         , ('progressspirit','waakaaboon') \
         , ('BSHQ','neokyle') \
         , ('Yulieta','paulyrich') \
         , ('LasAntOne','pongopigmayiss') \
         , ('sasukekun22','PeaceOnEarth123') \
         , ('neokyle','ctseng') \
         , ('dimonitxus','vac') \
         , ('rezarito','guitres2007') \
         , ('alejandrojazzmetal','kemadordcdman') \
         , ('rpoland','tommygauthier') \
         , ('caccataylor','BillyMacMusic') \
         , ('simonjung','rockhelterskelter') \
         , ('picasso79','przemkam') \
         , ('eastvanmungo','patzu') \
         , ('CARADEYONOFUI','elizabeth2212') \
         , ('mathdoy','sickboy888') \
         , ('Direwolf','username999999999') \
         , ('marks6338','alwiap15') \
         , ('euphemistic','TheLKfanClub') \
         , ('thomasdaniel','MAXI230384') \
         , ('paris1919','orkestas') \
         , ('ThePrairiePrankster','Klause') \
         , ('javiflamenko','pekerrecho10') \
         , ('asherel','keppler') \
         , ('camaronnuestro','soygitano') \
         , ('SoloGuitaristNet','musiquesimilia') \
         , ('javiflamenko','Funesolea') \
         , ('1santos1','Dixierocks20') \
         , ('ThePrairiePrankster','Thor3000') \
         , ('iburl','askox') \
         , ('Levesque999','wecurlupanddie') \
         , ('SoloGuitaristNet','HansVonz') \
         , ('juanitochiguesque','nandowainwright') \
         , ('euphemistic','tasilow') \
         , ('BSHQ','Hellbillyriot42') \
         , ('ELCIDVIVAR','tomsanti') \
         , ('amigomusica','Suldarr') \
         , ('FlamencoConrad','camaronnuestro') \
         , ('MadV','uniqlomixer') \
         , ('spockula','buffalax') \
         , ('CARADEYONOFUI','ELCIDVIVAR') \
         , ('WPPTV','toddcarey') \
         , ('scoobyman','edbazs') \
         , ('srsnoid','PetroBPettson') \
         , ('NilezII','caveman78') \
         , ('Direwolf','stoneagelightning') \
         , ('simonjung','mrmanok') \
         , ('jazzfunkshizzle','universalmusicgroup') \
         , ('pencilpusher30','lsfilho') \
         , ('Nd179','officialstp') \
         , ('evolvin1','remos74') \
         , ('iburl','WarpRecords') \
         , ('superh7','mongillo') \
         , ('1santos1','shirleybeans') \
         , ('blonduo','Dragonzito') \
         , ('bird5050','ta55555555') \
         , ('todgemistro','shapirog') \
         , ('Louie566','SteveMjazz') \
         , ('thebeatlessound','netyta') \
         , ('euphemistic','tjitta25') \
         , ('rpoland','realmusicchicago') \
         , ('amigomusica','FearlessRecords') \
         , ('somebod','LuiscmckII') \
         , ('tobakala','cnrsport') \
         , ('HairFarmer','austinstein') \
         , ('neokyle','mozman68') \
         , ('pencilpusher30','pitchipich') \
         , ('euphemistic','BOLSHEVIK06') \
         , ('russelljdj','Scarab75') \
         , ('schumann23','videosimard') \
         , ('sgbnyc','Artiga88') \
         , ('davidaron','username999999999') \
         , ('FranksValli','viniciusmc') \
         , ('scoobyman','coolrobbie2002') \
         , ('LeGauchiste','toshyocom') \
         , ('fritzita','oskpeturs') \
         , ('bird5050','troubleclef') \
         , ('somebod','isagio') \
         , ('rspaceball','caseymagic') \
         , ('trfrasier','expositionanormale') \
         , ('expositionanormale','rhubarbcream') \
         , ('HenfieldWill','blondfalcon2') \
         , ('gusyverde','neurophilemichel') \
         , ('JPL1982','GameFreak7885') \
         , ('rspaceball','deenichols') \
         , ('progressspirit','xfactorfansite') \
         , ('jazzfunkshizzle','Brutal561E') \
         , ('tasilow','euphemistic') \
         , ('erikmongrain','nichols8917') \
         , ('AntoineDufour','CARADEYONOFUI') \
         , ('evolvin1','jwcfree') \
         , ('expositionanormale','RikiRude') \
         , ('elizabeth2212','ilamvm') \
         , ('amigomusica','jonedryb') \
         , ('simonjung','CrunchyWacko') \
         , ('FranksValli','rockonyemenofwar') \
         , ('simonjung','dfrohnenalfred') \
         , ('austinmayor','TSMusVid') \
         , ('intheairtonight','Kushrynada') \
         , ('HenfieldWill','agwtube') \
         , ('mathdoy','maldroid1') \
         , ('rezarito','bandasurdo') \
         , ('koioti','blacklotus007') \
         , ('maxider','brian278') \
         , ('simonjung','lasourisdesvilles') \
         , ('camaronnuestro','karlys18') \
         , ('1santos1','TotallyDionne') \
         , ('marks6338','BenRodenburg') \
         , ('scoobyman','Musician81') \
         , ('camaronnuestro','ritaclips') \
         , ('thomasdaniel','tonictao') \
         , ('koioti','corporeal') \
         , ('expositionanormale','ralphdude') \
         , ('davidaron','grunzy') \
         , ('edugiansante','daniloprado') \
         , ('russelljdj','eltonb') \
         , ('tasilow','vip01') \
         , ('Vreci','superpicker') \
         , ('LasAntOne','BigEvilSDMF') \
         , ('emalyse','DHaynesakafingerrs') \
         , ('kerryberrywerry','masterrofl') \
         , ('LasAntOne','yokorevolver') \
         , ('srsnoid','joooosu') \
         , ('lerxtdude','adam02') \
         , ('raw64life','RAKIMWILLIAM') \
         , ('buffalax','vemendoza') \
         , ('blonduo','TheDoorsMusic') \
         , ('KeizerSosa','Sudarev') \
         , ('fritzita','ElGofion') \
         , ('somebod','EnigmaSolved') \
         , ('matteo19','Sharpmarkers') \
         , ('Levesque999','j0ndaily') \
         , ('cevarius','malcolmmcfly') \
         , ('erikmongrain','edugiansante') \
         , ('progressspirit','suziemcneil') \
         , ('intheairtonight','davidnyren') \
         , ('camaronnuestro','donmauro24') \
         , ('HairFarmer','LoveUprising') \
         , ('neokyle','melissa3110') \
         , ('davidaron','squane') \
         , ('simonjung','daandrums') \
         , ('masterrofl','Mustainexd') \
         , ('dodgeturbonut','pbhack') \
         , ('masterrofl','peyoteshaman') \
         , ('elizabeth2212','fredcyr') \
         , ('gusyverde','gelido95') \
         , ('maxider','scmm42') \
         , ('alejandrojazzmetal','marRicardo') \
         , ('scoobyman','wildeyed') \
         , ('eastvanmungo','Committed77') \
         , ('ELCIDVIVAR','whiteSM05') \
         , ('jazzerkris','matteo19') \
         , ('marcusd','denSMSgt') \
         , ('emalyse','miguelcanel') \
         , ('picasso79','tapsomebong') \
         , ('dodgeturbonut','jonemmerling') \
         , ('fritzita','djkag2006') \
         , ('phever','plasticwrapcharlie') \
         , ('DrCochambre','pabloancieta') \
         , ('JPL1982','letthemetalflow') \
         , ('expositionanormale','OrangeTabbyCat3') \
         , ('dimonitxus','pakoflamenco') \
         , ('tiston69','metebelis') \
         , ('Levesque999','dardanella') \
         , ('LasAntOne','Frutson5') \
         , ('Louie566','DoowopRick') \
         , ('tlsbr','reikiaddict') \
         , ('tasilow','hand42') \
         , ('DJFPhantomPhan','WarnerMusicBelgium') \
         , ('alexvmusic','carhornsinapril') \
         , ('gatasalvaje79','Ro18') \
         , ('Geezer3d','vip01') \
         , ('picasso79','magicbologna') \
         , ('mattharding2718','NuoVisoProductions') \
         , ('carhornsinapril','largofilm') \
         , ('AntoineDufour','TrueFireTV') \
         , ('LasAntOne','vodkaa1') \
         , ('1santos1','sebas71') \
         , ('Nd179','butalcain') \
         , ('phever','bigblueplanet') \
         , ('pencilpusher30','orphanim') \
         , ('kissdemonette','80sLady') \
         , ('alejandrojazzmetal','french4clouds') \
         , ('thebeatlessound','TheSw1tch') \
         , ('russelljdj','musicmasterez') \
         , ('tradestaff','JOoOoDo') \
         , ('buffalax','Mag141414') \
         , ('soygitano','BambaMaker') \
         , ('Levesque999','PetesBloodyHand') \
         , ('sgbnyc','calamityjames') \
         , ('dimonitxus','gato3d') \
         , ('dimonitxus','Saxatilis9876') \
         , ('JPL1982','JoeSiegler') \
         , ('DrCochambre','jonnyb666') \
         , ('rezarito','haithamflamenco') \
         , ('thomasdaniel','vicarinatutugal') \
         , ('Louie566','stoffershorty') \
         , ('gusyverde','WagnerOperas') \
         , ('tiston69','hn999') \
         , ('tasilow','Haeronthegreat') \
         , ('maxider','cosmicrocketman') \
         , ('alexvmusic','RadioMad') \
         , ('roadrunnerrecords','lomoncurry') \
         , ('tlsbr','Terriman') \
         , ('Direwolf','noremorse9') \
         , ('dodgeturbonut','DissolvedGirl') \
         , ('NilezII','naom6654321') \
         , ('roadrunnerrecords','ColinQuinn') \
         , ('NilezII','TotalVoltageVault') \
         , ('BOLSHEVIK06','Sabaton') \
         , ('expositionanormale','Xexezinha') \
         , ('LasAntOne','Metalized') \
         , ('tobakala','harmypochi') \
         , ('phever','garyhopkins') \
         , ('sgbnyc','ConnorTheSlayer') \
         , ('juanitochiguesque','fasumia') \
         , ('NilezII','gloria6699') \
         , ('Orville9999','hemo1985') \
         , ('erikmongrain','picasso79') \
         , ('iburl','drunkhorse') \
         , ('tlsbr','nfscoy') \
         , ('asherel','eag200') \
         , ('rezarito','pixaninny') \
         , ('killersoundz','JenniferH') \
         , ('alejandrojazzmetal','dancohen') \
         , ('ELCIDVIVAR','usharimau') \
         , ('progressspirit','billyjoel') \
         , ('pencilpusher30','ssg410') \
         , ('DrCochambre','crappco') \
         , ('erikmongrain','Levesque999') \
         , ('cevarius','Theorem') \
         , ('expositionanormale','ridgraycr') \
         , ('1santos1','rpmime') \
         , ('rezarito','javiflamenko') \
         , ('ELCIDVIVAR','Miko1p') \
         , ('sasukekun22','Filmstudent89') \
         , ('somebod','MKT2') \
         , ('snowbot79','enmasse') \
         , ('pedrogamo','bohemion') \
         , ('soygitano','tHoM0r') \
         , ('rezarito','stvolo') \
         , ('gusyverde','mikus1983') \
         , ('Yulieta','mgng') \
         , ('rezarito','dhrrltka') \
         , ('BSHQ','iburl') \
         , ('HenfieldWill','postingoldtapes') \
         , ('asherel','FattyJubbo') \
         , ('Levesque999','showbiz87') \
         , ('Louie566','fngrpckr') \
         , ('HenfieldWill','eltonb') \
         , ('mathdoy','blocpartyofficial') \
         , ('falconsweetwater','WPPTV') \
         , ('iburl','CLARUSBARTEL72') \
         , ('ELCIDVIVAR','Hafor') \
         , ('fritzita','CelinemaniacsCom') \
         , ('fritzita','johngreek') \
         , ('intheairtonight','mickm305') \
         , ('neokyle','paswitzer') \
         , ('alejandrojazzmetal','deathcrab') \
         , ('tasilow','nmhu77') \
         , ('expositionanormale','morrisseymylove') \
         , ('koioti','erikmongrain') \
         , ('scoobyman','MorseMoose79') \
         , ('tasilow','kenstannuurd') \
         , ('roadrunnerrecords','musich3ad') \
         , ('BSHQ','1santos1') \
         , ('tommygauthier','trfrasier') \
         , ('HenfieldWill','billieandmarty') \
         , ('SoloGuitaristNet','jazzmannl') \
         , ('tlsbr','AcidPhase15') \
         , ('neokyle','okeastron') \
         , ('berg444','WPPTV') \
         , ('thebeatlessound','blondie92126') \
         , ('Vreci','omdunet') \
         , ('FlamencoConrad','Funesolea') \
         , ('javiflamenko','esmirriao84') \
         , ('scoobyman','SyClopps') \
         , ('mathdoy','wichitarecordings') \
         , ('juanitochiguesque','Zeolum') \
         , ('HenfieldWill','TCGUITAR') \
         , ('evolvin1','MattAlexan') \
         , ('NilezII','Teenagekicks') \
         , ('elizabeth2212','germanyonline') \
         , ('gusyverde','ophelia2006') \
         , ('emalyse','S1N15T3R') \
         , ('elizabeth2212','backpackdave') \
         , ('Geezer3d','superpicker') \
         , ('Geezer3d','euphemistic') \
         , ('rezarito','siroco1988') \
         , ('Vreci','missritaho') \
         , ('iburl','schnickschnack1990') \
         , ('NilezII','homeandgardenmusic') \
         , ('progressspirit','jinxmaster777') \
         , ('rezarito','acompas') \
         , ('phever','strawberrymj') \
         , ('Gusyverde2','CompayHabana') \
         , ('totalgrobanite','Belanna42') \
         , ('russelljdj','cevarius') \
         , ('Louie566','southpawjay') \
         , ('kerryberrywerry','rebel072162') \
         , ('Orville9999','rpoland') \
         , ('dodgeturbonut','djcomet') \
         , ('Geezer3d','BenOwensGuitardotcom') \
         , ('thebeatlessound','xalexisx3') \
         , ('davidaron','usedMTVpromos') \
         , ('SoloGuitaristNet','Molgav') \
         , ('eastvanmungo','mindbank') \
         , ('gusyverde','edved10062') \
         , ('progressspirit','tivogliobene85') \
         , ('matteo19','jamieza') \
         , ('schumann23','luisguilhermeolbertz') \
         , ('eastvanmungo','isac1977') \
         , ('masterrofl','gdbvsdzgdsfbdfg') \
         , ('LasAntOne','jester420') \
         , ('somebod','LEGENDSOFJAZZ') \
         , ('fritzita','bigotitus') \
         , ('bird5050','caroline372') \
         , ('MadV','meesteraldous') \
         , ('HenfieldWill','lubitel11') \
         , ('SoloGuitaristNet','classicalguild') \
         , ('progressspirit','idareTocare') \
         , ('dimonitxus','rubiarock') \
         , ('thebeatlessound','BeatnikManfred') \
         , ('intheairtonight','mrdodo') \
         , ('HenfieldWill','Scot90230') \
         , ('Direwolf','BVMHardcorePunkTV') \
         , ('Orville9999','dbneeld') \
         , ('asherel','enemy4monotoniclife') \
         , ('ELCIDVIVAR','dangelo87') \
         , ('asherel','Gemear') \
         , ('jazzfunkshizzle','TankSallott') \
         , ('amigomusica','whatisreal01') \
         , ('SoloGuitaristNet','kabemty') \
         , ('tiston69','blacklotus007') \
         , ('Nd179','ballbeg') \
         , ('marks6338','ballesterom') \
         , ('emalyse','thestandingroom') \
         , ('BOLSHEVIK06','pippintk') \
         , ('neokyle','fabiocchi') \
         , ('Geezer3d','vdj') \
         , ('asherel','luckyoda') \
         , ('scoobyman','walkinthemire') \
         , ('Vreci','Napolianboo') \
         , ('roadrunnerrecords','tracydanger') \
         , ('WPPTV','enjoybellwoods') \
         , ('iburl','heavyrevolution') \
         , ('picasso79','peterfriday') \
         , ('edugiansante','petahx') \
         , ('srsnoid','cbrace') \
         , ('ELCIDVIVAR','losderibadumia') \
         , ('BSHQ','marcusd') \
         , ('rpoland','AntoineDufour') \
         , ('koioti','PAULASOVERAL') \
         , ('gusyverde','CarpentersSuperstars') \
         , ('schumann23','songbird1987') \
         , ('evolvin1','Haeronthegreat') \
         , ('euphemistic','Tranquility12') \
         , ('masterrofl','insandiego') \
         , ('somebod','oatzy') \
         , ('totalgrobanite','MishaFromPoland') \
         , ('Nd179','rockonyemenofwar') \
         , ('totalgrobanite','loveholic6364') \
         , ('GShton','Ayhoe') \
         , ('Louie566','lyijynen') \
         , ('emalyse','texasitch') \
         , ('rspaceball','corporatecountrysuck') \
         , ('BOLSHEVIK06','euphemistic') \
         , ('mattharding2718','boh3m3') \
         , ('spockula','ShoTown') \
         , ('soygitano','jasabet') \
         , ('edugiansante','maknstfe') \
         , ('srsnoid','amarelo') \
         , ('killersoundz','monmonsnow') \
         , ('WPPTV','moogdroog') \
         , ('Nd179','hartiganxxx') \
         , ('musicmasterez','Fstyl') \
         , ('intheairtonight','srappose') \
         , ('NilezII','litigioushipster') \
         , ('alejandrojazzmetal','zombierichard') \
         , ('Yulieta','sabrien') \
         , ('javiflamenko','norteflamenco') \
         , ('1santos1','bert839550') \
         , ('eastvanmungo','blindlemonlemonhead') \
         , ('fritzita','VJmongo') \
         , ('NilezII','PUNKsir') \
         , ('soygitano','dukels') \
         , ('FlamencoConrad','vargasxerez') \
         , ('Orville9999','heyjude421') \
         , ('trfrasier','davidaron') \
         , ('JPL1982','anononiem') \
         , ('guitaroo1','stazisummers') \
         , ('rezarito','jazzerman') \
         , ('gusyverde','zinta2000') \
         , ('SoloGuitaristNet','kanengiser') \
         , ('thebeatlessound','BabyJavier21') \
         , ('maxider','PatyDifusa') \
         , ('iburl','dancebuffet') \
         , ('amigomusica','glorfo') \
         , ('willbill0587','Dizkneelande') \
         , ('lerxtdude','shumpy') \
         , ('tiston69','rpoland') \
         , ('BSHQ','fpdiii') \
         , ('asherel','harryuhf') \
         , ('WPPTV','wichitarecordings') \
         , ('evolvin1','vip01') \
         , ('Tranquility12','katyskystar') \
         , ('BenOrdinary','godisatan') \
         , ('davidaron','scotchhollow') \
         , ('Direwolf','maxeypad') \
         , ('alejandrojazzmetal','pakoflamenco') \
         , ('tiston69','jonbrod') \
         , ('thebeatlessound','Artero') \
         , ('RadioMad','Casshern25') \
         , ('falconsweetwater','n0b0dysbitch0') \
         , ('thebeatlessound','chiwawette33') \
         , ('blonduo','reenee') \
         , ('Louie566','ccbopcarp') \
         , ('somebod','ToxicEmbrace') \
         , ('FranksValli','snark12') \
         , ('neokyle','oysteryogurt') \
         , ('progressspirit','FredMartins') \
         , ('tasilow','tjitta25') \
         , ('elizabeth2212','xyzmikey1') \
         , ('roadrunnerrecords','heavymetalsourcepr') \
         , ('soygitano','okfer') \
         , ('mathdoy','secretcityrecords') \
         , ('ELCIDVIVAR','datishet') \
         , ('maxider','divingdonkey') \
         , ('LasAntOne','chronicbluntman420') \
         , ('juanitochiguesque','mastervictor') \
         , ('fritzita','LAZ61') \
         , ('kissdemonette','MusicIdiotSavante') \
         , ('Levesque999','PTL654321') \
         , ('elizabeth2212','mlhkb8') \
         , ('lerxtdude','Foskateer') \
         , ('rezarito','chatarrito') \
         , ('fritzita','pakomusicalatino') \
         , ('gusyverde','arkeolog99') \
         , ('Vreci','honouredman') \
         , ('tiston69','Elwing06') \
         , ('Nd179','paulcapewell') \
         , ('camaronnuestro','luchango') \
         , ('JPL1982','EntertainmentUnited') \
         , ('amigomusica','gamzer') \
         , ('Levesque999','rchaisson') \
         , ('progressspirit','percivaljulio') \
         , ('elizabeth2212','davidjepank') \
         , ('picasso79','type3secretion') \
         , ('musicmasterez','mitzy1234') \
         , ('killersoundz','Suchar') \
         , ('elizabeth2212','spaceace40') \
         , ('camaronnuestro','edwardnorton') \
         , ('HenfieldWill','ChuckAkins') \
         , ('Vreci','KyuRoo') \
         , ('HenfieldWill','B0zz3') \
         , ('realmusicchicago','frankorrall') \
         , ('scoobyman','Endrias') \
         , ('tlsbr','afonso85') \
         , ('killersoundz','davidvaldes') \
         , ('amigomusica','rpoland') \
         , ('alejandrojazzmetal','llafutaal') \
         , ('nowitslemon','lettieb13') \
         , ('thomasdaniel','gustavopoeta') \
         , ('somebod','aamaa') \
         , ('emalyse','shifzr') \
         , ('1santos1','herrstahlhoefer') \
         , ('somebod','worldchallenger') \
         , ('Geezer3d','WCHANDY') \
         , ('tiston69','Czitar') \
         , ('CARADEYONOFUI','asiantiger01') \
         , ('thebeatlessound','GeorgeWaxstetter') \
         , ('SoloGuitaristNet','hulldanfan') \
         , ('evolvin1','rpoland') \
         , ('HairFarmer','wiljay') \
         , ('javiflamenko','bartola67') \
         , ('gusyverde','foniberico') \
         , ('evolvin1','playguitarsolos') \
         , ('sasukekun22','awkwardpictures') \
         , ('1santos1','wwwSceneFedcom') \
         , ('eastvanmungo','sassasdotorg') \
         , ('hsage','JimmyToast') \
         , ('edugiansante','druman44') \
         , ('amigomusica','weba') \
         , ('evolvin1','tiston69') \
         , ('picasso79','kurdtss') \
         , ('russelljdj','gusyverde') \
         , ('guitaroo1','halipino') \
         , ('HairFarmer','AlonzoMosleyFBI') \
         , ('FranksValli','diegodf87') \
         , ('tasilow','Pasquerel') \
         , ('iburl','phatterboy') \
         , ('Louie566','fopstra') \
         , ('JPL1982','Lion7718') \
         , ('jazzfunkshizzle','ReverendBeastly') \
         , ('sasukekun22','bizkitroach666') \
         , ('Vreci','criltunieddu') \
         , ('DalimaaFashmire','freedomworksfilms') \
         , ('lerxtdude','richcapo') \
         , ('rpoland','erikmongrain') \
         , ('musicmasterez','carlosaleon') \
         , ('progressspirit','sotti84') \
         , ('camaronnuestro','galleis2') \
         , ('scoobyman','universalmusicgroup') \
         , ('progressspirit','OriginalDrDil') \
         , ('Tranquility12','GuitarPlayerMatthew') \
         , ('69Lovett','personatv') \
         , ('evolvin1','NAUDOPRD') \
         , ('euphemistic','simonjung') \
         , ('ELCIDVIVAR','wiggindude') \
         , ('koioti','Croketas') \
         , ('tlsbr','leifa') \
         , ('AntoineDufour','GMiner') \
         , ('tlsbr','supermilinha') \
         , ('expositionanormale','tisizemenrai') \
         , ('phever','ludwig222') \
         , ('AntoineDufour','FlamencoConrad') \
         , ('HenfieldWill','maceoaus') \
         , ('FlamencoConrad','rezarito') \
         , ('bird5050','pizadio') \
         , ('nowitslemon','hmbscully') \
         , ('thomasdaniel','davebarrett81') \
         , ('NilezII','elenarendezvous') \
         , ('lerxtdude','diablofn') \
         , ('Yulieta','HolgerregloH') \
         , ('soygitano','sintoniasaintgermain') \
         , ('NilezII','dexter63') \
         , ('Direwolf','eu396') \
         , ('camaronnuestro','DefinitiveStar') \
         , ('kissdemonette','kootallica') \
         , ('rezarito','feefree') \
         , ('Geezer3d','jjdaes') \
         , ('koioti','MMLeung') \
         , ('neokyle','Followthatkite') \
         , ('elizabeth2212','russelljdj') \
         , ('HenfieldWill','lupine22') \
         , ('russelljdj','69Lovett') \
         , ('gusyverde','giottocimabue') \
         , ('cevarius','elimk') \
         , ('neokyle','NicksterMarsh') \
         , ('DalimaaFashmire','MMLeung') \
         , ('gusyverde','Samanosuke2') \
         , ('soygitano','slashhatim') \
         , ('roadrunnerrecords','AHicks200') \
         , ('bird5050','emixdub') \
         , ('HenfieldWill','Americansquirm') \
         , ('Levesque999','bakachibi') \
         , ('gusyverde','phaedor') \
         , ('simonjung','LickByNeckDotCom') \
         , ('sasukekun22','nyoung27') \
         , ('amigomusica','martinvist') \
         , ('scoobyman','darkerstuff') \
         , ('Levesque999','TheClash0711') \
         , ('camaronnuestro','Consulina') \
         , ('FlamencoConrad','dimonitxus') \
         , ('BSHQ','austinmayor') \
         , ('progressspirit','raphaeldesi2') \
         , ('FlamencoConrad','tallerdemusics') \
         , ('simonjung','ESCManiac') \
         , ('bsarles','niquele') \
         , ('LasAntOne','strewth') \
         , ('russelljdj','66BUDOKAN') \
         , ('emalyse','aerboarder') \
         , ('ELCIDVIVAR','Damalmansa') \
         , ('Lezcanomg','lossilencios') \
         , ('trfrasier','Nd179') \
         , ('aprilsaurus','roio420') \
         , ('WPPTV','dylg') \
         , ('Vreci','isntitironicRACOON') \
         , ('WPPTV','umvideo') \
         , ('todgemistro','killersoundz') \
         , ('ELCIDVIVAR','operationuranus') \
         , ('trfrasier','BDP62') \
         , ('FranksValli','TheRealJohnnyAngel') \
         , ('gusyverde','seitsuku') \
         , ('cevarius','ImperfectxCircle') \
         , ('Direwolf','fleafly') \
         , ('iburl','athenian1977') \
         , ('jazzfunkshizzle','deliciousvinyl') \
         , ('camaronnuestro','elmagopickup') \
         , ('progressspirit','bigwhitneyfan') \
         , ('euphemistic','ljubisab') \
         , ('HairFarmer','GlennCripes') \
         , ('Louie566','ToxicEmbrace') \
         , ('DJFPhantomPhan','carrotjuice78') \
         , ('lerxtdude','Lams9999') \
         , ('JosephO75','markdw40') \
         , ('superh7','McCartney8897') \
         , ('tiston69','ZackKim') \
         , ('koioti','guitar122334') \
         , ('trfrasier','tiston69') \
         , ('CARADEYONOFUI','gatasalvaje79') \
         , ('trfrasier','Direwolf') \
         , ('HenfieldWill','deepfreezevideo') \
         , ('buffalax','Junttidiskokunkku') \
         , ('Nd179','blonduo') \
         , ('todgemistro','buffalax') \
         , ('simonjung','jazzsanjavier') \
         , ('Levesque999','argondamn') \
         , ('phever','MrsDinoCrocetti') \
         , ('erikmongrain','willbill0587') \
         , ('davidaron','kubes') \
         , ('dimonitxus','TJenlared') \
         , ('bird5050','sebas71') \
         , ('simonjung','onemorecupofcoffee1') \
         , ('kissdemonette','DOWN2WHISKEY') \
         , ('javiflamenko','maikecau') \
         , ('AntoineDufour','roadrunnerrecords') \
         , ('trfrasier','asherel') \
         , ('lancetrumbull','idekan') \
         , ('lerxtdude','avondmaal') \
         , ('pencilpusher30','lakme') \
         , ('maxider','haveyouseenmygoal') \
         , ('amigomusica','nolimits67') \
         , ('DJFPhantomPhan','HARRY24') \
         , ('eastvanmungo','gastronomist') \
         , ('pedrogamo','nephilim3') \
         , ('jazzfunkshizzle','OldhamAthletic87KTF') \
         , ('titosiroco','halherta') \
         , ('Geezer3d','vicioustruth') \
         , ('DJFPhantomPhan','gonainie') \
         , ('Louie566','TwangTown') \
         , ('expositionanormale','Sethtann') \
         , ('eastvanmungo','blackstarkitten') \
         , ('Louie566','bird5050') \
         , ('Levesque999','Bukk3tbot') \
         , ('tommygauthier','jazzerkris') \
         , ('totalgrobanite','googirl') \
         , ('Geezer3d','TampaFred') \
         , ('picasso79','artscrafts') \
         , ('realmusicchicago','russelljdj') \
         , ('intheairtonight','cinc') \
         , ('FlamencoConrad','javiflamenko') \
         , ('expositionanormale','afiendishthingy') \
         , ('AntoineDufour','rpoland') \
         , ('DJFPhantomPhan','fatgirlgrobie') \
         , ('superh7','tradestaff') \
         , ('LasAntOne','argondamn') \
         , ('sasukekun22','steamrocks') \
         , ('javiflamenko','rusoeldelantonia') \
         , ('JPL1982','NuclearBlastEurope') \
         , ('bird5050','TravisBickle') \
         , ('Orville9999','rhythmstick') \
         , ('neokyle','videogum') \
         , ('elizabeth2212','latin60') \
         , ('koioti','rpoland') \
         , ('HairFarmer','garyhopkins') \
         , ('sgbnyc','evandronew') \
         , ('Yulieta','pulsepi') \
         , ('SoloGuitaristNet','gregplaysthestick') \
         , ('NilezII','conquestfordeath32') \
         , ('jazzfunkshizzle','courageousjohnny') \
         , ('simonjung','PiatyElefant') \
         , ('progressspirit','tinaarenafanes') \
         , ('tlsbr','superraiden') \
         , ('1santos1','perri23') \
         , ('jazzerkris','alejandrojazzmetal') \
         , ('jazzfunkshizzle','VICERecordings') \
         , ('somebod','PasianEntertainment') \
         , ('BOLSHEVIK06','PamBeatabet') \
         , ('matteo19','MerkinAbowt') \
         , ('picasso79','Fallschirmjager') \
         , ('killersoundz','babygus93') \
         , ('thebeatlessound','chikka1971') \
         , ('realmusicchicago','BSHQ') \
         , ('FlamencoConrad','soygitano') \
         , ('thebeatlessound','NinoRivera') \
         , ('gusyverde','MissVerdugo') \
         , ('bird5050','figgybit') \
         , ('Levesque999','vinkes') \
         , ('scoobyman','ISTMuso') \
         , ('SoloGuitaristNet','FilomenaMorettiVIDS') \
         , ('Louie566','musiciansworkshop') \
         , ('CARADEYONOFUI','nowitslemon') \
         , ('Geezer3d','tasilow') \
         , ('BOLSHEVIK06','siggi5153') \
         , ('HenfieldWill','Hippekuln') \
         , ('LasAntOne','quinny63') \
         , ('WPPTV','oxlabb') \
         , ('LasAntOne','skunkyfunk') \
         , ('camaronnuestro','omar2x') \
         , ('BSHQ','NilezII') \
         , ('LasAntOne','HateSphereSickness') \
         , ('bird5050','dutchfellow') \
         , ('picasso79','grandiosity') \
         , ('davidaron','jacquesmees') \
         , ('sasukekun22','michaelsmusicservice') \
         , ('realmusicchicago','berg444') \
         , ('simonjung','sonybmg') \
         , ('eastvanmungo','claddagh15') \
         , ('neokyle','renewenergy') \
         , ('koioti','danielperson') \
         , ('koioti','sasukekun22') \
         , ('tiston69','gamzer') \
         , ('Geezer3d','ubhankband') \
         , ('LasAntOne','PetesBloodyHand') \
         , ('masterrofl','TravBurcham') \
         , ('NilezII','nembutal') \
         , ('scoobyman','asturmod2') \
         , ('soygitano','pakoflamenco') \
         , ('sasukekun22','tneorg') \
         , ('BenOrdinary','sunserious') \
         , ('Vreci','jwcfree') \
         , ('DJFPhantomPhan','LoveTH14') \
         , ('elizabeth2212','emzypoo3') \
         , ('asherel','suparni') \
         , ('euphemistic','ultrarobin') \
         , ('BOLSHEVIK06','ludwigtrap') \
         , ('killersoundz','wiljay') \
         , ('koioti','ZackKim') \
         , ('edugiansante','wcapellini') \
         , ('LasAntOne','nfscoy') \
         , ('lancetrumbull','funky2714') \
         , ('asherel','Trakse') \
         , ('DJFPhantomPhan','primative276') \
         , ('expositionanormale','homewalk') \
         , ('javiflamenko','gitaniyaheredia') \
         , ('DJFPhantomPhan','romire') \
         , ('gusyverde','PuertoRicanDivas') \
         , ('somebod','RCRENTER') \
         , ('davidaron','Greyful') \
         , ('neokyle','carneirooo') \
         , ('camaronnuestro','caaaroooooo') \
         , ('roadrunnerrecords','fastfocustv') \
         , ('intheairtonight','itat80') \
         , ('musicmasterez','chico75pi') \
         , ('russelljdj','paris1919') \
         , ('trfrasier','MorningDewUS') \
         , ('emalyse','wackkuntucky') \
         , ('simonjung','itsartolie') \
         , ('DJFPhantomPhan','rizferd') \
         , ('soygitano','charnes') \
         , ('eastvanmungo','Nouveauxromo') \
         , ('fritzita','moresco63') \
         , ('sasukekun22','beet1ejuicex3') \
         , ('willbill0587','BiggerThanYou') \
         , ('edugiansante','maurilyn') \
         , ('somebod','galfredos') \
         , ('FranksValli','aarnouddegroen') \
         , ('rezarito','euphemistic') \
         , ('sgbnyc','ricomachiavelli') \
         , ('soygitano','itsartolie') \
         , ('euphemistic','evolvin1') \
         , ('Nd179','mirageuk') \
         , ('buffalax','Update0704') \
         , ('BSHQ','Hellbettie13') \
         , ('somebod','kman518') \
         , ('amigomusica','yurilane') \
         , ('lancetrumbull','romainblast') \
         , ('mathdoy','jimmyjoeroche') \
         , ('JPL1982','abstractlogix23') \
         , ('fritzita','Stephpekis') \
         , ('elizabeth2212','doer62') \
         , ('Nd179','Lakin24') \
         , ('BOLSHEVIK06','Haeronthegreat') \
         , ('expositionanormale','modcentric') \
         , ('Moiseocb','xupy') \
         , ('schumann23','deldea') \
         , ('WPPTV','doradorecords') \
         , ('soygitano','gasol777') \
         , ('somebod','jayeltee') \
         , ('asherel','TheDLShow') \
         , ('fritzita','CARADEYONOFUI') \
         , ('buffalax','panch85') \
         , ('fritzita','langwave') \
         , ('Geezer3d','SilviaKs') \
         , ('alejandrojazzmetal','Stillborn01') \
         , ('masterrofl','flectz') \
         , ('pencilpusher30','alvastarr') \
         , ('somebod','frommelxp') \
         , ('killersoundz','blacklotus007') \
         , ('soygitano','GigiBrasil') \
         , ('trfrasier','dodgeturbonut') \
         , ('iburl','petertvkill') \
         , ('gusyverde','raskolnikovxxl') \
         , ('eastvanmungo','lomiek') \
         , ('AntoineDufour','todgemistro') \
         , ('euphemistic','Vreci') \
         , ('kawryan','razel01') \
         , ('Yulieta','moodyb') \
         , ('somebod','cozmo') \
         , ('emalyse','Nafoute') \
         , ('russelljdj','julianpineirua') \
         , ('soygitano','weirdcollector') \
         , ('alejandrojazzmetal','akoff') \
         , ('amigomusica','druman44') \
         , ('euphemistic','masterrofl') \
         , ('Direwolf','theotherone61') \
         , ('DJFPhantomPhan','fantacolaspezi') \
         , ('neokyle','blogsarefordogs') \
         , ('HenfieldWill','JAustinDuke') \
         , ('BOLSHEVIK06','diOud') \
         , ('FranksValli','terminusj') \
         , ('eastvanmungo','makijackal') \
         , ('SoloGuitaristNet','katonatwins') \
         , ('marks6338','norske3n') \
         , ('BenOrdinary','TayZonday') \
         , ('HairFarmer','drednought77') \
         , ('rezarito','soygitano') \
         , ('intheairtonight','corben47') \
         , ('JPL1982','rainbow301') \
         , ('tasilow','guitarjjte') \
         , ('Hellbillyriot42','marcusd') \
         , ('NilezII','saylawgun') \
         , ('JPL1982','keysnovello') \
         , ('progressspirit','upfahler') \
         , ('JPL1982','lauranbri') \
         , ('blonduo','opevans') \
         , ('sgbnyc','robertorocky') \
         , ('1santos1','doule') \
         , ('roadrunnerrecords','metalscenetv') \
         , ('CARADEYONOFUI','fritzita') \
         , ('jazzfunkshizzle','greenmillcorp') \
         , ('neokyle','iruvtea') \
         , ('intheairtonight','carlus88') \
         , ('lancetrumbull','jonboy123456') \
         , ('intheairtonight','bootslover84') \
         , ('SoloGuitaristNet','GuitarRusso') \
         , ('progressspirit','dgv19711') \
         , ('rezarito','ritaclips') \
         , ('edugiansante','michaellou') \
         , ('Direwolf','classics2dvdDOTcom') \
         , ('NilezII','93or93') \
         , ('Levesque999','masterwiz26') \
         , ('amigomusica','russaac') \
         , ('pencilpusher30','Ricquer') \
         , ('Direwolf','hippieschnitzel') \
         , ('tradestaff','BayTaper') \
         , ('kerryberrywerry','GuitarPlayerMatthew') \
         , ('DrCochambre','Condu100') \
         , ('emalyse','DrMabuse66') \
         , ('eastvanmungo','outrun') \
         , ('HenfieldWill','jackliveshere2') \
         , ('progressspirit','langwave') \
         , ('elizabeth2212','modnocbmallari') \
         , ('soygitano','deniro20') \
         , ('camaronnuestro','antoniomanco') \
         , ('NilezII','pauliethepunk') \
         , ('tlsbr','Chapmanfan') \
         , ('matteo19','iheartguitars83') \
         , ('titosiroco','ahoy16') \
         , ('69Lovett','420stud') \
         , ('tasilow','rpoland') \
         , ('iburl','Guliv3r') \
         , ('lancetrumbull','skankbaggins') \
         , ('progressspirit','lightning49') \
         , ('Louie566','soFeinVideo') \
         , ('guitaroo1','AlecsMundt') \
         , ('neokyle','esyooee') \
         , ('erikmongrain','rpoland') \
         , ('HairFarmer','mikerjohnson') \
         , ('somebod','zindabada') \
         , ('kawryan','Styles217') \
         , ('Geezer3d','saitow') \
         , ('MadV','cheeryvibez') \
         , ('mattharding2718','NewNuma') \
         , ('srsnoid','PoisonIvy1983') \
         , ('matteo19','mayermusic') \
         , ('intheairtonight','spazmodica2012') \
         , ('FranksValli','CafeDaria') \
         , ('lancetrumbull','drummerdude136') \
         , ('NilezII','gobacktogo') \
         , ('rezarito','matttheguitarist') \
         , ('sasukekun22','freakslique') \
         , ('masterrofl','0Mandarina0') \
         , ('killersoundz','limiardorock') \
         , ('fritzita','neslibek') \
         , ('JPL1982','MattTS01') \
         , ('thebeatlessound','4sky13') \
         , ('paris1919','grullu') \
         , ('russelljdj','ThePrairiePrankster') \
         , ('julianpineirua','panchopistolas22') \
         , ('dodgeturbonut','fpe') \
         , ('guitaroo1','tradestaff') \
         , ('trfrasier','bsarles') \
         , ('blonduo','fhita') \
         , ('simonjung','66BUDOKAN') \
         , ('Tranquility12','euphemistic') \
         , ('thomasdaniel','RickRudesMustache') \
         , ('koioti','blaubeeri666') \
         , ('tiston69','wildbabydragon') \
         , ('SoloGuitaristNet','st1969') \
         , ('ifstudents','NRDCflix') \
         , ('soygitano','andreasoberg') \
         , ('amigomusica','tjitta25') \
         , ('killersoundz','mattrach') \
         , ('DalimaaFashmire','ifstudents') \
         , ('Direwolf','Partyslammer') \
         , ('edugiansante','qech') \
         , ('tlsbr','megbro') \
         , ('progressspirit','Albertine2006') \
         , ('fritzita','CelineAndRene') \
         , ('FlamencoConrad','SoloGuitaristNet') \
         , ('pencilpusher30','myredroom') \
         , ('SoloGuitaristNet','salomesandoval') \
         , ('todgemistro','JosephO75') \
         , ('rezarito','nldisco') \
         , ('BDP62','tpet32') \
         , ('austinmayor','footfoot1983') \
         , ('1santos1','MrPhotomatic') \
         , ('Orville9999','lightman') \
         , ('mathdoy','steakcognitif') \
         , ('TheLKfanClub','showbizmanager9') \
         , ('elizabeth2212','williebeable2c') \
         , ('WPPTV','domthomas1') \
         , ('soygitano','whiteSM05') \
         , ('russelljdj','FranksValli') \
         , ('neokyle','msusparty2000') \
         , ('killersoundz','kikoshred') \
         , ('bird5050','sgtpepper2') \
         , ('tlsbr','jbbaja') \
         , ('amigomusica','Funkonaut') \
         , ('koioti','universalmusicgroup') \
         , ('Moiseocb','semillanegra00') \
         , ('BenOrdinary','pauldullson') \
         , ('davidaron','jazzster123') \
         , ('expositionanormale','Fury') \
         , ('elizabeth2212','zahnyx') \
         , ('ELCIDVIVAR','jaumequalsevol') \
         , ('ELCIDVIVAR','denvercx') \
         , ('javiflamenko','LAGUATEKE') \
         , ('tlsbr','trinity1528') \
         , ('bird5050','retrovintage') \
         , ('BOLSHEVIK06','Snidress') \
         , ('raw64life','heavyarms117') \
         , ('somebod','locho36') \
         , ('trfrasier','hsage') \
         , ('scoobyman','bert839550') \
         , ('CARADEYONOFUI','totalgrobanite') \
         , ('todgemistro','oligore') \
         , ('JPL1982','Karkhash') \
         , ('tlsbr','luizdamata') \
         , ('euphemistic','amigomusica') \
         , ('blonduo','shatterdwing') \
         , ('intheairtonight','loulou7803') \
         , ('Louie566','gtrcoach') \
         , ('elizabeth2212','vds123vds123') \
         , ('spockula','pecomaru') \
         , ('Vreci','rpoland') \
         , ('elizabeth2212','redbaron863') \
         , ('Geezer3d','tjitta25') \
         , ('Levesque999','lethrneck4') \
         , ('HenfieldWill','enunc8r') \
         , ('soygitano','titosiroco') \
         , ('Levesque999','thedude62') \
         , ('tlsbr','danielflorencio') \
         , ('ELCIDVIVAR','anrongliang') \
         , ('thebeatlessound','Ramiroquai') \
         , ('thebeatlessound','vparadis') \
         , ('BOLSHEVIK06','gamzer') \
         , ('Vreci','strewth') \
         , ('srsnoid','FibonacciPrower') \
         , ('amigomusica','powerload') \
         , ('simonjung','vgarambone') \
         , ('neokyle','monkeytail713') \
         , ('Geezer3d','hilldk11') \
         , ('roadrunnerrecords','denovodahl') \
         , ('LasAntOne','shaf747') \
         , ('emalyse','Salfordian') \
         , ('Levesque999','bruckkk') \
         , ('eastvanmungo','dieselbytes') \
         , ('expositionanormale','RavenNation') \
         , ('thebeatlessound','grimaldo21') \
         , ('Geezer3d','BASSMAN455') \
         , ('SoloGuitaristNet','blhsing') \
         , ('simonjung','jasabet') \
         , ('LasAntOne','dawnnamara') \
         , ('Louie566','7arsehle6') \
         , ('trfrasier','rspaceball') \
         , ('eltonb','EndaMcC') \
         , ('bird5050','pujaben') \
         , ('jazzfunkshizzle','bearshimmy1') \
         , ('LasAntOne','slymetal') \
         , ('picasso79','espeem') \
         , ('DJFPhantomPhan','wayeleongoh') \
         , ('tasilow','sapo75') \
         , ('pencilpusher30','janemonheit') \
         , ('NilezII','stever1957') \
         , ('gusyverde','CantStandYaCostanza') \
         , ('lerxtdude','zizter') \
         , ('Vreci','Stanbush86') \
         , ('edugiansante','lu4ofa') \
         , ('eastvanmungo','haaneepoo') \
         , ('expositionanormale','Lucifuge') \
         , ('sasukekun22','gotitans999') \
         , ('neokyle','nuthead25') \
         , ('BOLSHEVIK06','itaydovrin') \
         , ('gusyverde','beatdacy') \
         , ('raw64life','universalmusicgroup') \
         , ('lerxtdude','Firebirdth') \
         , ('alejandrojazzmetal','hossenff') \
         , ('sasukekun22','MMLeung') \
         , ('FlamencoConrad','titosiroco') \
         , ('eastvanmungo','NezHEAD66') \
         , ('elizabeth2212','drdoowop') \
         , ('TheLKfanClub','billyjoel') \
         , ('trfrasier','Greg08101995') \
         , ('tiston69','juliocvr17') \
         , ('soygitano','eclypso') \
         , ('fritzita','rushdan') \
         , ('scoobyman','david140863') \
         , ('simonjung','TOMSOUNDS') \
         , ('koioti','Kewen') \
         , ('DJFPhantomPhan','dramaqueen43') \
         , ('rezarito','jazzerkris') \
         , ('scoobyman','noinfluence') \
         , ('Geezer3d','FrostyMorn') \
         , ('soygitano','verme87') \
         , ('evolvin1','maharg11') \
         , ('tlsbr','CitySlang') \
         , ('masterrofl','misterdopeman') \
]

pagerank = PageRank(nodes, edges, True)

ranks = pagerank.ranking()

for node, rank in ranks:
    print str((node,rank))

print 'nodes: %d' % len(nodes)
print 'edges: %d' % len(edges)

print time.gmtime()
